version: '3.8'

services:
  web:
    build: .
    command: gunicorn accuconnect.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/accuconnect
      - ./log:/log
    ports:
      - "8000:8000"
    env_file:
      - .env